Add payee compo added
Rajkumar-MP/FELearning-Transfer pull request #19
Opened 2021-03-02 13:21 UTC by Nayana-2607

2021-03-03 13:28 UTC, Rajkumar-MP commented
@Nayana-2607 resolve the conflict

2021-03-05 04:26 UTC, Rajkumar-MP requested changes

2021-03-05 04:26 UTC, Rajkumar-MP commented on package.json
> +    "node-modules": "^1.0.1",
why node-mdules and webpack-dev-server added here ?

2021-03-05 04:26 UTC, Rajkumar-MP commented on src/Components/fe-new-payee/FeNewPayee.js
> +import '@lion/button/';
is this valid ?

2021-03-05 04:28 UTC, Nayana-2607 commented on src/Components/fe-new-payee/FeNewPayee.js
> +import '@lion/button/';
I will correct the code

2021-03-05 04:31 UTC, Nayana-2607 commented on package.json
> +    "node-modules": "^1.0.1",
Removed the extra depenedecies

2021-03-05 07:06 UTC, Rajkumar-MP approved these changes, later dismissed

2021-03-05 07:06 UTC, Rajkumar-MP commented on package.json
> +    "deep-equal": "^2.0.5",
why we need this ?

2021-03-05 07:09 UTC, Nayana-2607 commented on package.json
> +    "deep-equal": "^2.0.5",
I will check and remove

2021-03-05 12:20 UTC, Rajkumar-MP submitted a review, later dismissed

2021-03-05 12:25 UTC, alekhya66 submitted a review, later dismissed

2021-03-08 10:15 UTC, shadushazzz submitted a review, later dismissed

2021-03-08 10:53 UTC, shadushazzz approved these changes

2021-03-08 10:55 UTC, alekhya66 approved these changes

2021-03-08 11:56 UTC, Rajkumar-MP approved these changes

2021-03-08 12:13 UTC, merged