feat/accountdetailspage
Rajkumar-MP/FELearning-Transfer pull request #28
Opened 2021-03-10 07:16 UTC by shadushazzz

2021-03-10 08:28 UTC, Rajkumar-MP commented on src/Pages/AccountsdetailsPage/AccountdetailsPage.js
> +    return data;
you dont need to return the data, you need to store it in `this.data` bcz it was used in the page

2021-03-11 11:14 UTC, Rajkumar-MP requested changes

2021-03-11 11:14 UTC, Rajkumar-MP commented on src/Pages/AccountsdetailsPage/AccountdetailsPage.js
> +      this.isError = true;
you need to trigger request update to reflect it

2021-03-11 11:14 UTC, Rajkumar-MP commented on src/Pages/AccountsdetailsPage/AccountdetailsPage.js
> +    <fe-notification type="error" label="Failed to fetched details" class ="${
added it as translation

2021-03-12 14:53 UTC, Rajkumar-MP requested changes

2021-03-12 14:53 UTC, Rajkumar-MP commented on src/Pages/AccountsdetailsPage/AccountdetailsPage.js
> +        url: '/accountinfo/925548553975232',
try to pass the id `925548553975232` from parent, because you will get this data once login is success

2021-03-12 14:53 UTC, Rajkumar-MP commented on src/Pages/AccountsdetailsPage/AccountdetailsPage.js
> +      this.requestUpdate();
u need to put after the value change, bcz it will start render before your change, so sometimes it will affect it

2021-03-18 05:18 UTC, Rajkumar-MP requested changes

2021-03-18 05:18 UTC, Rajkumar-MP commented on src/Pages/AccountsdetailsPage/AccountdetailsPage.js
> +      data: { type: Object },
its an Array

2021-03-18 05:20 UTC, shadushazzz commented on src/Pages/AccountsdetailsPage/AccountdetailsPage.js
> +      data: { type: Object },
Ok will  change

2021-03-18 14:07 UTC, Rajkumar-MP approved these changes

2021-03-18 14:17 UTC, Nayana-2607 approved these changes

2021-03-18 14:28 UTC, alekhya66 approved these changes

2021-03-18 14:29 UTC, merged